### ISSUE TITLE
Error: Unable to deserialize response with Content-Type application/JSON

### ISSUE THREAD

**Issue by kat-truong** [paypal/Payouts-NodeJS-SDK#12]
Just today I am getting this issue when trying to make requests (fetching batch details or making a batch payout request) to Paypal using the Payouts SDK.

```

2021-04-19T03:26:40.996-05:00 | Error: Unable to deserialize response with Content-Type application/JSON. Supported decodings are [/^application\/json/, /^text\/.*/, /^multipart\/.*/, /^application\/x-www-form-urlencoded/]
-- | --
  | 2021-04-19T03:26:40.996-05:00 | at Encoder.deserializeResponse (/app/website/node_modules/@paypal/paypalhttp/lib/paypalhttp/encoder.js:44:13)
  | 2021-04-19T03:26:40.996-05:00 | at PayPalHttpClient._parseResponse (/app/website/node_modules/@paypal/paypalhttp/lib/paypalhttp/http_client.js:184:34)
  | 2021-04-19T03:26:40.996-05:00 | at IncomingMessage.<anonymous> (/app/website/node_modules/@paypal/paypalhttp/lib/paypalhttp/http_client.js:134:28)
  | 2021-04-19T03:26:40.996-05:00 | at IncomingMessage.emit (events.js:327:22)
  | 2021-04-19T03:26:40.996-05:00 | at IncomingMessage.EventEmitter.emit (domain.js:467:12)
  | 2021-04-19T03:26:40.996-05:00 | at endReadableNT (internal/streams/readable.js:1327:12)
  | 2021-04-19T03:26:40.996-05:00 | at processTicksAndRejections (internal/process/task_queues.js:80:21)
  | 2021-04-19T03:26:41.342-05:00 | process exited with non-zero error code: 1
```

Please let me know if I can provide more info - though at the moment I'm unable to retrieve the actual request payload.

**Comment by tfang17** [comment]
Seeing same thing on old version of SDK.

**Comment by Sufiane** [comment]
having the same issue here !

**Comment by Sufiane** [comment]
i think the error lies beneath here: https://github.com/paypal/paypalhttp_node/issues/5

**Comment by tfang17** [comment]
When did this error start appearing for you guys? For me it was 4/17/21. Wondering why it is happening now, given that there haven't been any new releases?

**Comment by kat-truong** [comment]
Everything was working fine for us yesterday morning (1am-6am PDT). 
This issue appeared for us this morning at around (1:26am PDT)

**Comment by Sufiane** [comment]
for us this morning (2021-04-19,  12h Paris/France time)

**Comment by Sufiane** [comment]
We think this is a server issue returning the wrong content-type (application/JSON instead of application/json) inside the paypal internal libs

**Comment by Sufiane** [comment]
I've made a PR on the dependency this SDK relies on, to handle both UPPER case & lower case content type for json:
https://github.com/paypal/paypalhttp_node/pull/6

**Comment by Eastkap** [comment]
same issue on my end..., completely paralysed. Hope ur PR is accepted @Sufiane

**Comment by andrewwiik** [comment]
Same issue

**Comment by erasmussenBHTP** [comment]
PayPal has resolved the issue and multiple GitHub users including myself have had successful payout calls. Updates were posted in the previously referenced issue in [paypalhttp_node](https://github.com/paypal/paypalhttp_node/issues/5)

**Comment by kat-truong** [comment]
Issue is fixed for me and seems fixed for several people in https://github.com/paypal/paypalhttp_node/issues/5 

Closing issue

**Comment by Sufiane** [comment]
This issue happened again in production for us today.

The fix does not seems to be live.

Could it be possible to fix this in the lib ?

**Comment by aninja8** [comment]
@Sufiane can you please provide a debug id?

**Comment by tfang17** [comment]
Also happened to us again today.

**Comment by aninja8** [comment]
@tfang17 can you please provide a debug id? the requests we checked all have lower case header

**Comment by Sufiane** [comment]
@aninja8 any news about this ?

**Comment by rajkumarpalani** [comment]
@Sufiane its resolved

**Comment by Sufiane** [comment]
@rajkumarpalani no udpate on this lib whatsoever though 🤔 
is there some strategy to avoid this problem in the future ?

**Comment by rajkumarpalani** [comment]
There is a fix applied on the server side to emit lower case mime type
Updates to SDK will be rolled out to handle case insensitive mime type to avoid any issues in future

**Comment by Udhayakumar1996** [comment]
how to soul this problem Content-Type: application/json
