### ISSUE TITLE
Typo error in readme.md F

### ISSUE THREAD

**Issue by mersib** [paypal/Payouts-NodeJS-SDK#5]
![image](https://user-images.githubusercontent.com/24504669/98669252-f47cde00-2372-11eb-801b-83626ea44558.png)

The argument in the line below function definition should be batchId not batch. Apologies in advance if I am wrong

**Comment by rajkumarpalani** [comment]
Thanks for reporting @mersib

Please feel free to provide a PR in future if you would like
