### ISSUE TITLE
payout working perfect in sandbox but throwing some error in live enviornmnet!

### ISSUE THREAD

**Issue by Hassantanveeer** [paypal/Payouts-NodeJS-SDK#8]
this is the error i am getting in live 
text: '{"name":"VALIDATION_ERROR","message":"Invalid request - see details","debug_id":"a641429b40e07","information_link":"https://developer.paypal.com/docs/api/payments.payouts-batch/#errors","details":[{"field":"items[0].receiver","location":"body","issue":"may not be null"}],"links":[]}'

**Comment by rajkumarpalani** [comment]
@Hassantanveeer can you check the payload that you have passed, seems you have missed a mandatory parameter as mentioned in the error response - `items[0].receiver`
